language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: szezz2YE+8jRxaiFAj81QRbZvAHyNC3m4ammGgYF3jeimsNt0Pjfq08D48nywlQYGaNsq5e2PKeUm8EGGAGUuyvwpXKWZAxyrQd2oaSpDXztDh4J46EktqRsERQsXKQL5hcRIrR/nkq13/wVnF/0KpRiG4kxd/2exTEaCJq9+B/VusdYBU/YK72HOatHl6DikM+UMKfaLjVLiuB3Gq8gbwWSyk6FhhZwpia6mw7GuF2mNdHPh7PiT6z21CxkfsgBKvzOR4YTVis2rrEQSXPlrLxKpNcqvkOoikuK5wa6LIniEXamiuUSChcEAWpLpGX4cflzQtSeonfKKR3ulghISqNOt/voPYFOGbus1msuWVfu9nXTg/w1p6EBP2J8YTkfE1ck7q5MGDbU/M241CtrrECt6R5aO8hEtMDeTHeHtjlvs4BznnMQPoKEF+kXW2R4Owzy6MwTOKQF+DIt4yyQFrBB7VF52oaESyC8pSgLCKwhxSSVq8HGdwkfzAniCJmO2WLZ5WnacF+rxEBe9SSm/ENCBQkFqjUnBD3crRab0PKXwXIeeJIanR8Hf4xdtXLd2E8n+pb9lt2OeZ+QjLABnfmAC8o9zqG6QFilv92SmvjGCqgiZ+VS1PClmdANOGAqneF2lAN14k0PtHSUdMx2f75xjKTvPlaowgdatVkPWUs=
  app: seepage
  on:
    repo: bibiqiqi/seepage
