language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: asL78MKTXcwNzSa+POLiI/hzt7YRH5c1ni1h+9hwXdXKLb0W0aicqEz6LUue7gkiiKByg+8NzXv7tNoS9mhnCbGqk6AZxmv4RZ+rlrTdc+Krmh8X5KcJLx32XGodkV0rx6iv1L5A85MJexYQjHLomOxsdPgu/4N+ahZyXhUW+TLLFB9GvFnDJdVyCnbO8K493Yw2bBvSVbFJmxSZKMOOHMeK61SkBtPgmiS3AzZ2jO4uaMDT79m63R560vzaNjnXRoDjnL6hdBqbQ+IgFO35oHLHBcZDXGJOF1ciZygm+x13K79+oCXQBzElGmPFvdqhg7zvazJmgcBge6vHAOnVpGEVuoR+HxY/85C8YapMvvUBJ0V7btTqd3BsA920Zm0zm+3g6pJZhcoQSpAfUAbS4lDBFsTccLLLqyLjyO3Iwmj7HEiLKHv9uzICkhqZq4JqrhIXVL9SsqnVEkC0XdNxDiPKzVUr55tIH8cKxiL2+wx5u7toneB1I8sYqlwxNDBeb017iF3f3NaDRZzJW3zCrDF9gKe3PDU0D1nI6EggoL7O/AI6wtCP9kCOTbQ0J32CoTnxRl6zn/oW1rMtQ0Z6loKjzDky1ucCyQy7a18Y+jmqeXMTEWOW6/r13/QObrDho2THyY/wsmHyqbsnxL22OUCQxwBEKu6UcR5AZL/AlIg=
  app: seepage-client
  on:
    repo: bibiqiqi/seepage
