language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: nO3CN7EHD88LeVSdiU2KdYxba9btUb5AtOR9IVWZP9ILhUQdtth55BFmmZ/nAOuxEf0C6x7LxU1g9PIgQe5kYctGhUYsCl1v51/VlQR1cv4+cglQIBY9quw2ceQydoU3hF4qZ9iT2l0PviuPqrQ/EiT441RuXEu5OT5Jy6bQ8MUCvgFMeBD1eJUSzuUVMWpbyB+VaowHpgUxdhmmFMJk65csE3VumJZP06zWlSxCulsWp2pJRc/hBmet6wkbJhvxA4XY7KuSEW8oh23p1bXvVTkYpjpl8JkTwAb4FP3GHXiS4TcfwTSocqXepKg5uH6MEYbmHEMJ9HJeF7ggQRzHZuWf9S3/OoTFfsSFoSy+pzaHUHT++nI9EN85z0UkaMoxLBcezehJG90mKadBGuE+4NTPSAKQUy9KGFW+O5hg/ys1INSvGDOWG2hqcFRYEXvpaevLJshl6vkqBlWqCU/KOLXg2Ep4QaW8xgSyU6Sbx6JgZEvJsA9Yu2LON7zq2SHyPVyF3bO7zdEWrzUYa5SwbhOEtkgySPJ2yWD1KRj1/ImYbUlIwAU58wYSNbGqtmE8kvzYMe+f0paL1TTxjL48RGnq+h5yQx40rwTRNDAzXCQwugesMZr87wSZ+z7tr0BDaQlMx6iw11dLJLSvl22tdrfBnJ+a7ic1UPpdYKyElpo=
  app: seepage-client
  on:
    repo: bibiqiqi/seepage
