language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: mnk++1dirW3Md8SeGHDZRilbYimfLomkgDRWExKZZjWkgbI4AgGFrtXo7CmTSjkCs6Nm36zANlmFKOm5uKcHls6PMxvMSomqlZUyuH51B3WQc0wLkvQnN8gZoZXFCtLdsTd8K6kjPsQ+jy7EXPZVdQaZZAVNpHjnKAAnt2IwsSD/O6fDkmf0llJtKta6QL/yEYje6BMSxrm/zKPstC4irxcAXzFME0q9HuFShxqzQIPr8rFgo/v5rvYsn6zSGOeXNb/b2Pyz3EaiwaWVd/5NcrSUtm9P9MGiXKlMh3hque0OI36gQwcOWT+7kZkm7CMfS7UCZJzpEFpUVigDwAN48eQQ79mcTgfRnkDLjWiQhTbuML7GS/1QrWwqai3fEt4xoYqm2R4LsS5fLh6pQ37ZhEnBvhra/PNWKoHdPOyyBkS9UK/FQCB8qlD6bGbgRYjNNVTP4vf5HUwJQQT+cH1WkxaZdie3KalENwvFM2TajRkuBJtYJMM9PlcSJPgaRZ6Bg8P4PYVkI5VsMQShK3dwpAABUeJQaS7WRnHMDa1OvpnnMFKm16+oUu0mE/ahw9WMUkOfYF2vCpVu/Qf5rhL4pGjcoxCP4UDjcVJ5yTgDvVzzQYarWYLGuF/b+82pYuklNU73RlOTTbDEfiWjubk9/xy5xQIPFQkuSMfHe+7ir0c=
  app: seepage-client
  on:
    repo: bibiqiqi/seepage
